### ISSUE TITLE
Unable to get working standalone

### ISSUE THREAD

**Issue by netcruiser2k10** [ainsey11/octopusenergy-consumption-metrics#30]
Hi
I am currently using this via a standalone application using ubuntu 22.04.3 LTS LXC container
I am having trouble getting the program to run, i install everything that is needed and put in the correct metrics that are needed however i keep getting the following error. 

(redacted)@LXC-OctoMon:/opt/octomon$ npm run start

> octopus-exporter@1.0.0 start
> node index.js

Starting Octopus Energy Consumption Metrics Container
Current Settings are:

        OCTO_API_KEY =(redacted)
        OCTO_ELECTRIC_MPAN = (redacted)
        OCTO_ELECTRIC_SN = (redacted)
        OCTO_GAS_MPAN = (redacted)
        OCTO_GAS_SN = (redacted)
        INFLUXDB_URL = https://TheHive:8086
        INFLUXDB_TOKEN = (redacted)
        INFLUXDB_ORG = home
        INFLUXDB_BUCKET = octomon
        LOOP_TIME = 60
        OCTO_ELECTRIC_COST = 29.62
        OCTO_GAS_COST = 7.8
        PAGE_SIZE = 100
        VOLUME_CORRECTION = 1.02264
        CALORIFIC_VALUE = 40.1
        JOULES_CONVERSION = 3.6

Polling data from octopus API
WARN: Write to InfluxDB failed (attempt: 1). Error: write EPROTO 00E86650427F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:

    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16) {
  errno: -71,
  code: 'EPROTO',
  syscall: 'write'
}
ERROR: Retry buffer closed with 500 items that were not written to InfluxDB! 
Error: write EPROTO 00E86650427F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:

    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16) {
  errno: -71,
  code: 'EPROTO',
  syscall: 'write'
}
Error submitting data to InfluxDB
Sleeping for: 60
x^Z
[1]+  Stopped                 npm run start

Can you help me figure out what is going wrong ?

Version of Nodejs installed is v21.1.0

Thanks In Advance

**Comment by netcruiser2k10** [comment]
On doing some tinkering i have found out what the issue was for the above how ever ive come upto another stumbling block. The script runs OK and has created the fields within the database but now it comes up with all the below and then stops. I have checked the database and nothing has been populated in it except for the fileds created. 

Polling data from octopus API
Octopus API response submitted to InfluxDB successfully
Sleeping for: 60
Polling data from octopus API
Error retrieving data from octopus API
AxiosError: socket hang up
    at AxiosError.from (/opt/octomon/node_modules/axios/dist/node/axios.cjs:825:14)
    at RedirectableRequest.handleRequestError (/opt/octomon/node_modules/axios/dist/node/axios.cjs:2971:25)
    at RedirectableRequest.emit (node:events:515:28)
    at eventHandlers.<computed> (/opt/octomon/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:515:28)
    at TLSSocket.socketOnEnd (node:_http_client:519:9)
    at TLSSocket.emit (node:events:527:35)
    at endReadableNT (node:internal/streams/readable:1589:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ECONNRESET',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: AxiosHeaders {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/1.3.5',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    auth: { username: '(redacted' },
    method: 'get',
    url: 'https://api.octopus.energy/v1/electricity-meter-points/1300051716996/meters/21J0023948/consumption?page_size=100',
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      highWaterMark: 16384,
      length: 0,
      corked: 0,
      onwrite: [Function: bound onwrite],
      writelen: 0,
      bufferedIndex: 0,
      pendingcb: 0,
      [Symbol(kState)]: 34357356,
      [Symbol(kBufferedValue)]: null
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'https:',
      path: '/v1/electricity-meter-points/1300051716996/meters/21J0023948/consumption?page_size=100',
      method: 'GET',
      headers: [Object: null prototype],
      agents: [Object],
      auth: '(redacted):',
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: 'api.octopus.energy',
      port: '',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/v1/electricity-meter-points/1300051716996/meters/21J0023948/consumption',
      search: '?page_size=100'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      _header: 'GET /v1/electricity-meter-points/1300051716996/meters/21J0023948/consumption?page_size=100 HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/1.3.5\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: api.octopus.energy\r\n' +
        'Authorization: Basic c2tfbGl2ZV9TaDU0b3RkWENyRXZVYnNDaHRZSWtjMEo6\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/v1/electricity-meter-points/1300051716996/meters/21J0023948/consumption?page_size=100',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: true,
      host: 'api.octopus.energy',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kChunkedBuffer)]: [],
      [Symbol(kChunkedLength)]: 0,
      [Symbol(kSocket)]: [TLSSocket],
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'https://(redacted):@api.octopus.energy/v1/electricity-meter-points/1300051716996/meters/21J0023948/consumption?page_size=100',
    [Symbol(kCapture)]: false
  },
  cause: Error: socket hang up
      at connResetException (node:internal/errors:787:14)
      at TLSSocket.socketOnEnd (node:_http_client:519:23)
      at TLSSocket.emit (node:events:527:35)
      at endReadableNT (node:internal/streams/readable:1589:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'ECONNRESET'
  }
}
/opt/octomon/index.js:83
        for await ( obj of electricresponse.data.results) {
                                            ^

TypeError: Cannot read properties of null (reading 'data')
    at boot (/opt/octomon/index.js:83:45)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v21.1.0

**Comment by netcruiser2k10** [comment]
Project Cancelled

**Comment by netcruiser2k10** [comment]
Project Cancelled due to no response

**Comment by ainsey11** [comment]
Updating to say that the errors are pretty self explanatory

first of all - you have an SSL problem, either the LXC container does not have a matching CA for the influxdb server, or octopus API, or you have a proxy/firewall doing SSL MITM.

neither are issues with the code. A quick google of the error would have told you that.

**Comment by ainsey11** [comment]
Issue can remain closed as not project related.
